services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goph_keeper
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      VIRTUAL_HOST: adminer.bc.local
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: hever

volumes:
  mysql: ~
