name: build

on:
  push:

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, darwin ] # linux, darwin, windows
        arch: [ amd64 ]   # amd64, 386
        include:
          - os: linux
            arch: amd64
            # -----
          - os: linux
            arch: arm64
            # -----
          - os: darwin
            arch: arm64
            # -----
          - os: freebsd
            arch: amd64
            # -----
          - os: ''
            arch: amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check out code
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download

      - name: Generate builder values
        id: values
        run: |
          echo "version=$(echo ${GITHUB_REF##*/} | sed -e 's/^[vV ]*//')" >> $GITHUB_OUTPUT
          echo "timestamp=$(echo $(date +%FT%T%z))" >> $GITHUB_OUTPUT
          echo "binary-ext=$(echo $(echo `[ ${{ matrix.os }} = 'windows' ] && echo '.exe'`))" >> $GITHUB_OUTPUT
          echo "dist-name=$(echo gophkeeper_${{ matrix.os }}_${{ matrix.arch }})" >> $GITHUB_OUTPUT

      - name: Compile binary file
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CLIENT_LDFLAGS: >-
            -X github.com/gam6itko/goph-keeper/internal/client/tui/root/model.buildVersion=${{ steps.values.outputs.version }}
            -X github.com/gam6itko/goph-keeper/internal/client/tui/root/model.buildDate=${{ steps.values.outputs.timestamp }}
        run: |
          mkdir "./build"
          go build -ldflags "$CLIENT_LDFLAGS" -o "./build/client" ./cmd/client
          go build -o "./build/server" ./cmd/server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.values.outputs.dist-name }}"
          path: "./build"
          if-no-files-found: error
          retention-days: 30
