name: gophkeeper

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
